spring.datasource:
  url: jdbc:mysql://whirl.cmbiwnhn72ot.us-west-2.rds.amazonaws.com:3306/whirldb
  username: whirlmaster
  password: WhirlMasterPassword
  driver-class-name: com.mysql.jdbc.Driver
  
server.port: 9090  
spring.jpa.show-sql: true  